"""Compile the pinned deck into monochrome artwork and on-demand text resources."""
import json
import struct
from pathlib import Path
from PIL import Image, ImageOps, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
cards = json.loads((ROOT / 'reference/cards.json').read_text())['cards']
major = ['The Fool', 'The Magician', 'The High Priestess', 'The Empress',
         'The Emperor', 'The Hierophant', 'The Lovers', 'The Chariot', 'Fortitude',
         'The Hermit', 'Wheel Of Fortune', 'Justice', 'The Hanged Man', 'Death',
         'Temperance', 'The Devil', 'The Tower', 'The Star', 'The Moon', 'The Sun',
         'The Last Judgment', 'The World']
ranks = ['Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
         'Ten', 'Page', 'Knight', 'Queen', 'King']
media, rows = [], []
# Small launcher mark: a card with a four-point star, drawn at native resolution.
icon=Image.new('1',(25,25),0)
draw=ImageDraw.Draw(icon)
draw.rounded_rectangle((5,1,21,23),radius=2,outline=1,width=2)
draw.polygon([(13,5),(15,10),(19,12),(15,14),(13,19),(11,14),(7,12),(11,10)],fill=1)
icon.save(ROOT/'resources/data/menu-icon.png')
media.append({'type':'bitmap','name':'IMAGE_MENU_ICON','file':'data/menu-icon.png','menuIcon':True})
for i, card in enumerate(cards):
    name = card['name']
    if name in major:
        filename = f'major-{major.index(name):02}.jpg'
    else:
        rank, suit = name.split(' of ')
        filename = f'{suit.lower()}-{ranks.index(rank)+1:02}.jpg'
    art = Image.open(ROOT / 'reference/art' / filename).convert('L')
    for kind, suffix, size in [('art', '', (72, 116)), ('art', '~chalk', (64, 104)), ('art', '~emery', (104, 168)), ('art', '~gabbro', (104, 168)), ('detail', '', (128, 208)), ('detail', '~emery', (184, 296)), ('detail', '~gabbro', (184, 296))]:
        # Keep the complete original card; letterbox rather than crop its title.
        fitted = ImageOps.contain(art, size, Image.Resampling.LANCZOS)
        page = Image.new('L', size, 255)
        page.paste(fitted, ((size[0]-fitted.width)//2, (size[1]-fitted.height)//2))
        bits = page.point(lambda p: 255 if p > 175 else 0).convert('1')
        (ROOT / f'resources/data/{kind}-{i}{suffix}.bin').write_bytes(struct.pack('<HH', *size) + bits.tobytes())
    text = (card['meaning_up'] + '\0' + card['meaning_rev'] + '\0').encode('utf-8')
    assert len(text) < 1024
    (ROOT / f'resources/data/text-{i}.bin').write_bytes(text)
    media += [{'type': 'raw', 'name': f'ART_{i}', 'file': f'data/art-{i}.bin'},
              {'type': 'raw', 'name': f'DETAIL_{i}', 'file': f'data/detail-{i}.bin'},
              {'type': 'raw', 'name': f'TEXT_{i}', 'file': f'data/text-{i}.bin'}]
    rows.append('{%s, RESOURCE_ID_ART_%d, RESOURCE_ID_DETAIL_%d, RESOURCE_ID_TEXT_%d}' % (json.dumps(name), i, i, i))
(ROOT / 'src/c/deck.h').write_text('// Generated by tools/assets.py from the pinned deck.\n'
    'typedef struct { const char *name; uint32_t art, detail, text; } Card;\n'
    'static const Card DECK[78] = {\n' + ',\n'.join(rows) + '\n};\n')
package = json.loads((ROOT / 'package.json').read_text())
package['pebble']['resources']['media'] = media
(ROOT / 'package.json').write_text(json.dumps(package, indent=2) + '\n')
print(f'Prepared {len(cards)} cards, upright/reversed text, and full-card/detail artwork for each display size.')
